require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'advanced_patterns_with_hook' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'advanced_patterns_with_hookTests' do
    inherit! :complete
    # Pods for testing
  end

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  use_native_modules!
  use_unimodules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'advanced_patterns_with_hook-tvOS' do
  # Pods for advanced_patterns_with_hook-tvOS

  target 'advanced_patterns_with_hook-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
